version: '3.8'
services:
  db:
    build: 
      context: ./services/db
      dockerfile: Dockerfile
    container_name: test-db
    expose:
      - 5432
    volumes:
      - ./flask-sqlalchemy-relation-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7426

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    container_name: test
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - './services/server:/usr/src/app'
    ports:
      - 8001:8000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:7426@db:5432/test_database
    depends_on:
      - db
